### ISSUE TITLE
论文

### ISSUE THREAD

**Issue by Kubuqi-Wu** [juchengquan/Two_Layer_EMS#1]
大神您好，很抱歉打扰您。请问您有没有发表过关于微电网优化配置这一块的论文

**Comment by juchengquan** [comment]
> 大神您好，很抱歉打扰您。请问您有没有发表过关于微电网优化配置这一块的论文

您好，抱歉回复晚了，刚刚看到您的留言。

我本人没有做过planning optimization。或许下面的几篇paper能给您一些思路，其中有将运营优化配置优化结合的场景。

- Z. Li, Y. Xu, X. Feng and Q. Wu, "Optimal Stochastic Deployment of Heterogeneous Energy Storage in a Residential Multi-Energy Microgrid with Demand-Side Management," in IEEE Transactions on Industrial Informatics, doi: 10.1109/TII.2020.2971227.
- Li, Zhengmao, and Yan Xu. "Optimal coordinated energy dispatch of a multi-energy microgrid in grid-connected and islanded modes." Applied Energy 210 (2018): 974-986.
