### ISSUE TITLE
请教第二次滚动优化的参考值

### ISSUE THREAD

**Issue by dongdong12311** [juchengquan/Two_Layer_EMS#2]
作者您好！读了您的程序收获很大。我在阅读程序的过程中，有一个小问题：
第二次滚动优化的参考值，看程序里面是采用的是优化的结果作为参考值？而不是上层的参考值？
打扰了！

**Comment by juchengquan** [comment]
> 作者您好！读了您的程序收获很大。我在阅读程序的过程中，有一个小问题：
> 第二次滚动优化的参考值，看程序里面是采用的是优化的结果作为参考值？而不是上层的参考值？
> 打扰了！

Hi @dongdong12311, 抱歉回复晚了😂

我没有太理解您的问题，不过第二层是采用的第一层的优化结果作为reference的，不是实际中设备的运行状态。
